dist: trusty
sudo: required
#osx_image: xcode8
language: java

os:
  - linux
#  - osx

env:
  - BAZEL_VERSION=0.8.1

before_install:
  - pwd
  - OS=linux
  - ARCH=x86_64
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION"
  - GH_ARTIFACT="bazel-$BAZEL_VERSION-installer-$OS-$ARCH.sh"
  - CI_BASE="http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-$ARCH/lastSuccessfulBuild/artifact/output/ci"
  - CI_ARTIFACT="bazel--installer.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - if [[ "$BAZEL_VERSION" == "HEAD" ]]; then CI_ARTIFACT="`wget -qO- $CI_BASE | grep -o 'bazel-[-_a-zA-Z0-9\.]*-installer.sh' | uniq`"; fi
  - if [[ "$BAZEL_VERSION" == "HEAD" ]]; then URL="$CI_BASE/$CI_ARTIFACT"; fi
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh
  - sudo pip install grpcio==1.6.0
  # Install etcd versions
  - cd /tmp; wget https://github.com/coreos/etcd/releases/download/v2.2.1/etcd-v2.2.1-linux-amd64.tar.gz
  - cd /opt; tar zxf /tmp/etcd-v2.2.1-linux-amd64.tar.gz
  - cd /tmp; wget https://github.com/coreos/etcd/releases/download/v3.2.12/etcd-v3.2.12-linux-amd64.tar.gz
  - cd /opt; tar zxf /tmp/etcd-v3.2.12-linux-amd64.tar.gz

script:
  - cd ${TRAVIS_BUILD_DIR}
  - bazel test //test/... --test_output=streamed

notifications:
  email: false

